### PR TITLE
Added a workaround for formatting dates and times in EFX 1 templates.

### PR DESCRIPTION
**Pull request by rousso**
Added a workaround to improve date formatting in EFX 1 templates (because EFX 1 lacks date/time formatting functions).

### CODE REVIEW

**Review by pdonohoe — COMMENTED** [review]
The code looks fine. But you are changing the separator between day, month and year from "-" to "/" - is that what you intend?

**Comment by rousso** [comment]
> The code looks fine. But you are changing the separator between day, month and year from "-" to "/" - is that what you intend?

That's what I got from Sylvan:
> The format of date and time, for any format (PDF/HTML) and any languages, will be as follows: 23/05/2023 20:59:32   UTC+01:00
> DD/MM/YYYY HH:MM:SS UTC+01:00

I took the liberty to omit the seconds from the time without asking but I believe that should be ok.

**Review by bertrand-lorentz — APPROVED** [review]
Looks OK.
Please note that the timezone will be display as "+02:00", without the mention of "UTC".

**Comment by rousso** [comment]
> Looks OK. Please note that the timezone will be display as "+02:00", without the mention of "UTC".

Here is what the XSL docs indicate:
> **Z** : timezone as a time offset from UTC, or if an alphabetic modifier is present the conventional name of a timezone (such as PST) 
> **z** : timezone as a time offset using GMT, for example GMT+1 or GMT-05:00. For this component there is a fixed prefix of GMT, or a localized variation thereof for the chosen language, and the presentation modifier controls the representation of the signed time offset that follows.

I would expect that UTC will be displayed unless there is a named timezone that can be used. What is the format string you propose?

**Comment by bertrand-lorentz** [comment]
From the examples in the doc (https://www.w3.org/TR/xpath-functions-31/):
image

I'm not sure what's the right format.

**Comment by pdonohoe** [comment]
The documentation states that "All dates and times in eForms XML shall be expressed in ISO-8601 format, with local time marked as an offset from Coordinated Universal Time." Up to now, we have output it in the same format, i.e. the "Z" format. I think we should keep doing this, unless instructed otherwise.

**Pull request merged**
